/**
 * GENERATED by scripts/gen-teams.ts from CollegeFootballData team info
 * (2026) and schedule Elo — do not edit by hand. Curated judgement calls
 * (coverage, front, scheme, noise, rivalries) live in ./curated.ts.
 */
export interface FbsTeamIdentity {
  id: string; espnId: number; abbr: string; school: string; mascot: string; conference: string;
  colors: [string, string];
  stadium: { name: string; city: string; dome: boolean; capacity: number; altitudeFt: number; lat: number; lng: number };
  /** Latest Elo from the schedule feed at generation time (null if unknown). */
  elo: number | null;
  logoUrl?: string;
}

export const FBS_SEASON = 2026;

export const FBS_TEAMS: FbsTeamIdentity[] = [
 {
  id: "boston-college",
  espnId: 103,
  abbr: "BC",
  school: "Boston College",
  mascot: "Eagles",
  conference: "ACC",
  colors: [
   "#8c2232",
   "#dbcca6"
  ],
  stadium: {
   name: "Alumni Stadium",
   city: "Chestnut Hill, MA",
   dome: false,
   capacity: 44500,
   altitudeFt: 131,
   lat: 42.335104,
   lng: -71.1664413
  },
  elo: 1406,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png"
 },
 {
  id: "california",
  espnId: 25,
  abbr: "CAL",
  school: "California",
  mascot: "Golden Bears",
  conference: "ACC",
  colors: [
   "#041e42",
   "#ffc72c"
  ],
  stadium: {
   name: "California Memorial Stadium",
   city: "Berkeley, CA",
   dome: false,
   capacity: 62467,
   altitudeFt: 411,
   lat: 37.8710434,
   lng: -122.2507729
  },
  elo: 1406,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png"
 },
 {
  id: "clemson",
  espnId: 228,
  abbr: "CLEM",
  school: "Clemson",
  mascot: "Tigers",
  conference: "ACC",
  colors: [
   "#f56600",
   "#522d80"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Clemson, SC",
   dome: false,
   capacity: 81500,
   altitudeFt: 675,
   lat: 34.6787737,
   lng: -82.8432428
  },
  elo: 1670,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png"
 },
 {
  id: "duke",
  espnId: 150,
  abbr: "DUKE",
  school: "Duke",
  mascot: "Blue Devils",
  conference: "ACC",
  colors: [
   "#00539b",
   "#ffffff"
  ],
  stadium: {
   name: "Wallace Wade Stadium",
   city: "Durham, NC",
   dome: false,
   capacity: 40004,
   altitudeFt: 338,
   lat: 35.9953688,
   lng: -78.9417564
  },
  elo: 1581,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png"
 },
 {
  id: "florida-state",
  espnId: 52,
  abbr: "FSU",
  school: "Florida State",
  mascot: "Seminoles",
  conference: "ACC",
  colors: [
   "#782f40",
   "#ceb888"
  ],
  stadium: {
   name: "Doak Campbell Stadium",
   city: "Tallahassee, FL",
   dome: false,
   capacity: 67277,
   altitudeFt: 64,
   lat: 30.4381692,
   lng: -84.3044032
  },
  elo: 1559,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png"
 },
 {
  id: "georgia-tech",
  espnId: 59,
  abbr: "GT",
  school: "Georgia Tech",
  mascot: "Yellow Jackets",
  conference: "ACC",
  colors: [
   "#b3a369",
   "#ffffff"
  ],
  stadium: {
   name: "Bobby Dodd Stadium",
   city: "Atlanta, GA",
   dome: false,
   capacity: 55000,
   altitudeFt: 916,
   lat: 33.7724449,
   lng: -84.3928054
  },
  elo: 1563,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png"
 },
 {
  id: "louisville",
  espnId: 97,
  abbr: "LOU",
  school: "Louisville",
  mascot: "Cardinals",
  conference: "ACC",
  colors: [
   "#c9001f",
   "#000000"
  ],
  stadium: {
   name: "L&N Federal Credit Union Stadium",
   city: "Louisville, KY",
   dome: false,
   capacity: 60000,
   altitudeFt: 455,
   lat: 38.2057621,
   lng: -85.7588141
  },
  elo: 1666,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png"
 },
 {
  id: "miami",
  espnId: 2390,
  abbr: "MIA",
  school: "Miami",
  mascot: "Hurricanes",
  conference: "ACC",
  colors: [
   "#f47321",
   "#005030"
  ],
  stadium: {
   name: "Hard Rock Stadium",
   city: "Miami Gardens, FL",
   dome: false,
   capacity: 64767,
   altitudeFt: 9,
   lat: 25.9579665,
   lng: -80.2388604
  },
  elo: 1842,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png"
 },
 {
  id: "nc-state",
  espnId: 152,
  abbr: "NCSU",
  school: "NC State",
  mascot: "Wolfpack",
  conference: "ACC",
  colors: [
   "#cc0000",
   "#ffffff"
  ],
  stadium: {
   name: "Carter-Finley Stadium",
   city: "Raleigh, NC",
   dome: false,
   capacity: 58000,
   altitudeFt: 384,
   lat: 35.8008001,
   lng: -78.7195655
  },
  elo: 1509,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png"
 },
 {
  id: "north-carolina",
  espnId: 153,
  abbr: "UNC",
  school: "North Carolina",
  mascot: "Tar Heels",
  conference: "ACC",
  colors: [
   "#7bafd4",
   "#13294b"
  ],
  stadium: {
   name: "Kenan Stadium",
   city: "Chapel Hill, NC",
   dome: false,
   capacity: 50500,
   altitudeFt: 419,
   lat: 35.9069294,
   lng: -79.0478889
  },
  elo: 1395,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png"
 },
 {
  id: "pittsburgh",
  espnId: 221,
  abbr: "PITT",
  school: "Pittsburgh",
  mascot: "Panthers",
  conference: "ACC",
  colors: [
   "#003594",
   "#ffb81c"
  ],
  stadium: {
   name: "Acrisure Stadium",
   city: "Pittsburgh, PA",
   dome: false,
   capacity: 68400,
   altitudeFt: 724,
   lat: 40.4467648,
   lng: -80.0157603
  },
  elo: 1576,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png"
 },
 {
  id: "smu",
  espnId: 2567,
  abbr: "SMU",
  school: "SMU",
  mascot: "Mustangs",
  conference: "ACC",
  colors: [
   "#d70000",
   "#0033a1"
  ],
  stadium: {
   name: "Gerald J. Ford Stadium",
   city: "University Park, TX",
   dome: false,
   capacity: 32000,
   altitudeFt: 556,
   lat: 32.8377223,
   lng: -96.7827859
  },
  elo: 1734,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png"
 },
 {
  id: "stanford",
  espnId: 24,
  abbr: "STAN",
  school: "Stanford",
  mascot: "Cardinal",
  conference: "ACC",
  colors: [
   "#8c1515",
   "#ffffff"
  ],
  stadium: {
   name: "Stanford Stadium",
   city: "Stanford, CA",
   dome: false,
   capacity: 50424,
   altitudeFt: 60,
   lat: 37.4345556,
   lng: -122.1611271
  },
  elo: 1408,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png"
 },
 {
  id: "syracuse",
  espnId: 183,
  abbr: "SYR",
  school: "Syracuse",
  mascot: "Orange",
  conference: "ACC",
  colors: [
   "#f76900",
   "#000e54"
  ],
  stadium: {
   name: "JMA Wireless Dome",
   city: "Syracuse, NY",
   dome: true,
   capacity: 49057,
   altitudeFt: 534,
   lat: 43.0362269,
   lng: -76.1363161
  },
  elo: 1288,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png"
 },
 {
  id: "virginia",
  espnId: 258,
  abbr: "UVA",
  school: "Virginia",
  mascot: "Cavaliers",
  conference: "ACC",
  colors: [
   "#232d4b",
   "#f84c1e"
  ],
  stadium: {
   name: "Scott Stadium",
   city: "Charlottesville, VA",
   dome: false,
   capacity: 61500,
   altitudeFt: 559,
   lat: 38.0311801,
   lng: -78.5137897
  },
  elo: 1652,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png"
 },
 {
  id: "virginia-tech",
  espnId: 259,
  abbr: "VT",
  school: "Virginia Tech",
  mascot: "Hokies",
  conference: "ACC",
  colors: [
   "#861f41",
   "#e87722"
  ],
  stadium: {
   name: "Lane Stadium",
   city: "Blacksburg, VA",
   dome: false,
   capacity: 65632,
   altitudeFt: 2074,
   lat: 37.2199873,
   lng: -80.4180643
  },
  elo: 1421,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png"
 },
 {
  id: "wake-forest",
  espnId: 154,
  abbr: "WAKE",
  school: "Wake Forest",
  mascot: "Demon Deacons",
  conference: "ACC",
  colors: [
   "#ceb888",
   "#2c2a29"
  ],
  stadium: {
   name: "Allegacy Federal Credit Union Stadium",
   city: "Winston-Salem, NC",
   dome: false,
   capacity: 31500,
   altitudeFt: 930,
   lat: 36.1305507,
   lng: -80.2545851
  },
  elo: 1520,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png"
 },
 {
  id: "army",
  espnId: 349,
  abbr: "ARMY",
  school: "Army",
  mascot: "Black Knights",
  conference: "American Athletic",
  colors: [
   "#000000",
   "#d3bc8d"
  ],
  stadium: {
   name: "Michie Stadium",
   city: "West Point, NY",
   dome: false,
   capacity: 38000,
   altitudeFt: 326,
   lat: 41.3874924,
   lng: -73.9640891
  },
  elo: 1527,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png"
 },
 {
  id: "charlotte",
  espnId: 2429,
  abbr: "CLT",
  school: "Charlotte",
  mascot: "49ers",
  conference: "American Athletic",
  colors: [
   "#005035",
   "#a49665"
  ],
  stadium: {
   name: "Jerry Richardson Stadium",
   city: "Charlotte, NC",
   dome: false,
   capacity: 15300,
   altitudeFt: 625,
   lat: 35.3105033,
   lng: -80.7401194
  },
  elo: 1182,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png"
 },
 {
  id: "east-carolina",
  espnId: 151,
  abbr: "ECU",
  school: "East Carolina",
  mascot: "Pirates",
  conference: "American Athletic",
  colors: [
   "#592a8a",
   "#fdc82f"
  ],
  stadium: {
   name: "Dowdy-Ficklen Stadium",
   city: "Greenville, NC",
   dome: false,
   capacity: 50000,
   altitudeFt: 63,
   lat: 35.5968486,
   lng: -77.364564
  },
  elo: 1562,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png"
 },
 {
  id: "florida-atlantic",
  espnId: 2226,
  abbr: "FAU",
  school: "Florida Atlantic",
  mascot: "Owls",
  conference: "American Athletic",
  colors: [
   "#003366",
   "#cc0000"
  ],
  stadium: {
   name: "FAU Stadium",
   city: "Boca Raton, FL",
   dome: false,
   capacity: 29419,
   altitudeFt: 12,
   lat: 26.3763763,
   lng: -80.1015759
  },
  elo: 1285,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png"
 },
 {
  id: "memphis",
  espnId: 235,
  abbr: "MEM",
  school: "Memphis",
  mascot: "Tigers",
  conference: "American Athletic",
  colors: [
   "#00498f",
   "#9c9ea1"
  ],
  stadium: {
   name: "Simmons Bank Liberty Stadium",
   city: "Memphis, TN",
   dome: false,
   capacity: 58325,
   altitudeFt: 297,
   lat: 35.1209429,
   lng: -89.977147
  },
  elo: 1541,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png"
 },
 {
  id: "navy",
  espnId: 2426,
  abbr: "NAVY",
  school: "Navy",
  mascot: "Midshipmen",
  conference: "American Athletic",
  colors: [
   "#00225b",
   "#b5a67c"
  ],
  stadium: {
   name: "Navy-Marine Corps Memorial Stadium",
   city: "Annapolis, MD",
   dome: false,
   capacity: 34000,
   altitudeFt: 35,
   lat: 38.9846985,
   lng: -76.5076335
  },
  elo: 1550,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png"
 },
 {
  id: "north-texas",
  espnId: 249,
  abbr: "UNT",
  school: "North Texas",
  mascot: "Mean Green",
  conference: "American Athletic",
  colors: [
   "#00853e",
   "#ffffff"
  ],
  stadium: {
   name: "DATCU Stadium",
   city: "Denton, TX",
   dome: false,
   capacity: 30850,
   altitudeFt: 652,
   lat: 33.203899,
   lng: -97.159245
  },
  elo: 1639,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png"
 },
 {
  id: "rice",
  espnId: 242,
  abbr: "RICE",
  school: "Rice",
  mascot: "Owls",
  conference: "American Athletic",
  colors: [
   "#00205b",
   "#c1c6c8"
  ],
  stadium: {
   name: "Rice Stadium",
   city: "Houston, TX",
   dome: false,
   capacity: 47000,
   altitudeFt: 23,
   lat: 29.7163297,
   lng: -95.4093261
  },
  elo: 1196,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png"
 },
 {
  id: "south-florida",
  espnId: 58,
  abbr: "USF",
  school: "South Florida",
  mascot: "Bulls",
  conference: "American Athletic",
  colors: [
   "#006747",
   "#cfc493"
  ],
  stadium: {
   name: "Raymond James Stadium",
   city: "Tampa, FL",
   dome: false,
   capacity: 65828,
   altitudeFt: 36,
   lat: 27.9758691,
   lng: -82.5033344
  },
  elo: 1682,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png"
 },
 {
  id: "temple",
  espnId: 218,
  abbr: "TEM",
  school: "Temple",
  mascot: "Owls",
  conference: "American Athletic",
  colors: [
   "#a41e35",
   "#ffffff"
  ],
  stadium: {
   name: "Lincoln Financial Field",
   city: "Philadelphia, PA",
   dome: false,
   capacity: 69879,
   altitudeFt: 10,
   lat: 39.9007995,
   lng: -75.1675414
  },
  elo: 1312,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png"
 },
 {
  id: "tulane",
  espnId: 2655,
  abbr: "TULN",
  school: "Tulane",
  mascot: "Green Wave",
  conference: "American Athletic",
  colors: [
   "#006747",
   "#418fde"
  ],
  stadium: {
   name: "Yulman Stadium",
   city: "New Orleans, LA",
   dome: false,
   capacity: 30000,
   altitudeFt: 0,
   lat: 29.944616,
   lng: -90.116692
  },
  elo: 1555,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png"
 },
 {
  id: "tulsa",
  espnId: 202,
  abbr: "TLSA",
  school: "Tulsa",
  mascot: "Golden Hurricane",
  conference: "American Athletic",
  colors: [
   "#003595",
   "#d0b787"
  ],
  stadium: {
   name: "Chapman Stadium",
   city: "Tulsa, OK",
   dome: false,
   capacity: 30000,
   altitudeFt: 773,
   lat: 36.1489175,
   lng: -95.9437853
  },
  elo: 1240,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png"
 },
 {
  id: "uab",
  espnId: 5,
  abbr: "UAB",
  school: "UAB",
  mascot: "Blazers",
  conference: "American Athletic",
  colors: [
   "#1a5632",
   "#fdb913"
  ],
  stadium: {
   name: "Protective Stadium",
   city: "Birmingham, AL",
   dome: false,
   capacity: 45000,
   altitudeFt: 614,
   lat: 33.5206824,
   lng: -86.8024326
  },
  elo: 1443,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png"
 },
 {
  id: "utsa",
  espnId: 2636,
  abbr: "UTSA",
  school: "UTSA",
  mascot: "Roadrunners",
  conference: "American Athletic",
  colors: [
   "#0c2340",
   "#f15a22"
  ],
  stadium: {
   name: "Alamodome",
   city: "San Antonio, TX",
   dome: true,
   capacity: 36582,
   altitudeFt: 661,
   lat: 29.4169834,
   lng: -98.4788143
  },
  elo: 1522,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png"
 },
 {
  id: "arizona",
  espnId: 12,
  abbr: "ARIZ",
  school: "Arizona",
  mascot: "Wildcats",
  conference: "Big 12",
  colors: [
   "#cc0033",
   "#003366"
  ],
  stadium: {
   name: "Arizona Stadium",
   city: "Tucson, AZ",
   dome: false,
   capacity: 50782,
   altitudeFt: 2435,
   lat: 32.2288054,
   lng: -110.9488677
  },
  elo: 1625,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png"
 },
 {
  id: "arizona-state",
  espnId: 9,
  abbr: "ASU",
  school: "Arizona State",
  mascot: "Sun Devils",
  conference: "Big 12",
  colors: [
   "#ffc627",
   "#8c1d40"
  ],
  stadium: {
   name: "Mountain America Stadium",
   city: "Tempe, AZ",
   dome: false,
   capacity: 65870,
   altitudeFt: 1182,
   lat: 33.4264471,
   lng: -111.9325005
  },
  elo: 1572,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png"
 },
 {
  id: "baylor",
  espnId: 239,
  abbr: "BAY",
  school: "Baylor",
  mascot: "Bears",
  conference: "Big 12",
  colors: [
   "#154734",
   "#ffb81c"
  ],
  stadium: {
   name: "McLane Stadium",
   city: "Waco, TX",
   dome: false,
   capacity: 45140,
   altitudeFt: 384,
   lat: 31.5582015,
   lng: -97.1156702
  },
  elo: 1506,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png"
 },
 {
  id: "byu",
  espnId: 252,
  abbr: "BYU",
  school: "BYU",
  mascot: "Cougars",
  conference: "Big 12",
  colors: [
   "#003da5",
   "#002e5d"
  ],
  stadium: {
   name: "LaVell Edwards Stadium",
   city: "Provo, UT",
   dome: false,
   capacity: 63470,
   altitudeFt: 4633,
   lat: 40.2575347,
   lng: -111.6545247
  },
  elo: 1666,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png"
 },
 {
  id: "cincinnati",
  espnId: 2132,
  abbr: "CIN",
  school: "Cincinnati",
  mascot: "Bearcats",
  conference: "Big 12",
  colors: [
   "#000000",
   "#e00122"
  ],
  stadium: {
   name: "Nippert Stadium",
   city: "Cincinnati, OH",
   dome: false,
   capacity: 40000,
   altitudeFt: 755,
   lat: 39.1312495,
   lng: -84.5161913
  },
  elo: 1480,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png"
 },
 {
  id: "colorado",
  espnId: 38,
  abbr: "COLO",
  school: "Colorado",
  mascot: "Buffaloes",
  conference: "Big 12",
  colors: [
   "#cfb87c",
   "#000000"
  ],
  stadium: {
   name: "Folsom Field",
   city: "Boulder, CO",
   dome: false,
   capacity: 50183,
   altitudeFt: 5361,
   lat: 40.0094746,
   lng: -105.266905
  },
  elo: 1396,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png"
 },
 {
  id: "houston",
  espnId: 248,
  abbr: "HOU",
  school: "Houston",
  mascot: "Cougars",
  conference: "Big 12",
  colors: [
   "#c8102e",
   "#ffffff"
  ],
  stadium: {
   name: "TDECU Stadium",
   city: "Houston, TX",
   dome: false,
   capacity: 40000,
   altitudeFt: 31,
   lat: 29.7219885,
   lng: -95.3491623
  },
  elo: 1508,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png"
 },
 {
  id: "iowa-state",
  espnId: 66,
  abbr: "ISU",
  school: "Iowa State",
  mascot: "Cyclones",
  conference: "Big 12",
  colors: [
   "#c8102e",
   "#f1be48"
  ],
  stadium: {
   name: "Jack Trice Stadium",
   city: "Ames, IA",
   dome: false,
   capacity: 61500,
   altitudeFt: 902,
   lat: 42.0139977,
   lng: -93.6357716
  },
  elo: 1586,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png"
 },
 {
  id: "kansas",
  espnId: 2305,
  abbr: "KU",
  school: "Kansas",
  mascot: "Jayhawks",
  conference: "Big 12",
  colors: [
   "#0051ba",
   "#e8000d"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Lawrence, KS",
   dome: false,
   capacity: 47000,
   altitudeFt: 902,
   lat: 38.9629418,
   lng: -95.2463686
  },
  elo: 1510,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png"
 },
 {
  id: "kansas-state",
  espnId: 2306,
  abbr: "KSU",
  school: "Kansas State",
  mascot: "Wildcats",
  conference: "Big 12",
  colors: [
   "#512888",
   "#ffffff"
  ],
  stadium: {
   name: "Bill Snyder Family Stadium",
   city: "Manhattan, KS",
   dome: false,
   capacity: 50000,
   altitudeFt: 1076,
   lat: 39.2020096,
   lng: -96.5938395
  },
  elo: 1616,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png"
 },
 {
  id: "oklahoma-state",
  espnId: 197,
  abbr: "OKST",
  school: "Oklahoma State",
  mascot: "Cowboys",
  conference: "Big 12",
  colors: [
   "#fe5c00",
   "#000000"
  ],
  stadium: {
   name: "Boone Pickens Stadium",
   city: "Stillwater, OK",
   dome: false,
   capacity: 55509,
   altitudeFt: 907,
   lat: 36.125673,
   lng: -97.066513
  },
  elo: 1240,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png"
 },
 {
  id: "tcu",
  espnId: 2628,
  abbr: "TCU",
  school: "TCU",
  mascot: "Horned Frogs",
  conference: "Big 12",
  colors: [
   "#4d1979",
   "#ffffff"
  ],
  stadium: {
   name: "Amon G. Carter Stadium",
   city: "Fort Worth, TX",
   dome: false,
   capacity: 46000,
   altitudeFt: 608,
   lat: 32.7096604,
   lng: -97.3680835
  },
  elo: 1598,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png"
 },
 {
  id: "texas-tech",
  espnId: 2641,
  abbr: "TTU",
  school: "Texas Tech",
  mascot: "Red Raiders",
  conference: "Big 12",
  colors: [
   "#c30020",
   "#000000"
  ],
  stadium: {
   name: "Jones AT&T Stadium",
   city: "Lubbock, TX",
   dome: false,
   capacity: 60454,
   altitudeFt: 3218,
   lat: 33.5910518,
   lng: -101.8728824
  },
  elo: 1870,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png"
 },
 {
  id: "ucf",
  espnId: 2116,
  abbr: "UCF",
  school: "UCF",
  mascot: "Knights",
  conference: "Big 12",
  colors: [
   "#000000",
   "#b4a169"
  ],
  stadium: {
   name: "FBC Mortgage Stadium",
   city: "Orlando, FL",
   dome: false,
   capacity: 44206,
   altitudeFt: 69,
   lat: 28.6079765,
   lng: -81.1927233
  },
  elo: 1465,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png"
 },
 {
  id: "utah",
  espnId: 254,
  abbr: "UTAH",
  school: "Utah",
  mascot: "Utes",
  conference: "Big 12",
  colors: [
   "#be0000",
   "#ffffff"
  ],
  stadium: {
   name: "Rice-Eccles Stadium",
   city: "Salt Lake City, UT",
   dome: false,
   capacity: 51444,
   altitudeFt: 4631,
   lat: 40.7599724,
   lng: -111.8488255
  },
  elo: 1817,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png"
 },
 {
  id: "west-virginia",
  espnId: 277,
  abbr: "WVU",
  school: "West Virginia",
  mascot: "Mountaineers",
  conference: "Big 12",
  colors: [
   "#eaaa00",
   "#002855"
  ],
  stadium: {
   name: "Milan Puskar Stadium",
   city: "Morgantown, WV",
   dome: false,
   capacity: 60000,
   altitudeFt: 1074,
   lat: 39.6502744,
   lng: -79.9551873
  },
  elo: 1360,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png"
 },
 {
  id: "illinois",
  espnId: 356,
  abbr: "ILL",
  school: "Illinois",
  mascot: "Fighting Illini",
  conference: "Big Ten",
  colors: [
   "#ff5f05",
   "#13294b"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Champaign, IL",
   dome: false,
   capacity: 60670,
   altitudeFt: 732,
   lat: 40.0993268,
   lng: -88.2359569
  },
  elo: 1563,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png"
 },
 {
  id: "indiana",
  espnId: 84,
  abbr: "IU",
  school: "Indiana",
  mascot: "Hoosiers",
  conference: "Big Ten",
  colors: [
   "#990000",
   "#ffffff"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Bloomington, IN",
   dome: false,
   capacity: 52656,
   altitudeFt: 760,
   lat: 39.1808959,
   lng: -86.5256217
  },
  elo: 2064,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/84.png"
 },
 {
  id: "iowa",
  espnId: 2294,
  abbr: "IOWA",
  school: "Iowa",
  mascot: "Hawkeyes",
  conference: "Big Ten",
  colors: [
   "#000000",
   "#ffcd00"
  ],
  stadium: {
   name: "Kinnick Stadium",
   city: "Iowa City, IA",
   dome: false,
   capacity: 69250,
   altitudeFt: 724,
   lat: 41.6586045,
   lng: -91.5510829
  },
  elo: 1791,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png"
 },
 {
  id: "maryland",
  espnId: 120,
  abbr: "MD",
  school: "Maryland",
  mascot: "Terrapins",
  conference: "Big Ten",
  colors: [
   "#ce1126",
   "#ffffff"
  ],
  stadium: {
   name: "SECU Stadium",
   city: "College Park, MD",
   dome: false,
   capacity: 51802,
   altitudeFt: 107,
   lat: 38.9903332,
   lng: -76.9473792
  },
  elo: 1424,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png"
 },
 {
  id: "michigan",
  espnId: 130,
  abbr: "MICH",
  school: "Michigan",
  mascot: "Wolverines",
  conference: "Big Ten",
  colors: [
   "#00274c",
   "#ffcb05"
  ],
  stadium: {
   name: "Michigan Stadium",
   city: "Ann Arbor, MI",
   dome: false,
   capacity: 107601,
   altitudeFt: 838,
   lat: 42.2658365,
   lng: -83.7486956
  },
  elo: 1690,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png"
 },
 {
  id: "michigan-state",
  espnId: 127,
  abbr: "MSU",
  school: "Michigan State",
  mascot: "Spartans",
  conference: "Big Ten",
  colors: [
   "#173f35",
   "#ffffff"
  ],
  stadium: {
   name: "Spartan Stadium",
   city: "East Lansing, MI",
   dome: false,
   capacity: 75005,
   altitudeFt: 836,
   lat: 42.7281474,
   lng: -84.4848526
  },
  elo: 1439,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png"
 },
 {
  id: "minnesota",
  espnId: 135,
  abbr: "MINN",
  school: "Minnesota",
  mascot: "Golden Gophers",
  conference: "Big Ten",
  colors: [
   "#7a0019",
   "#ffcc33"
  ],
  stadium: {
   name: "Huntington Bank Stadium",
   city: "Minneapolis, MN",
   dome: false,
   capacity: 50850,
   altitudeFt: 835,
   lat: 44.976525,
   lng: -93.2245462
  },
  elo: 1510,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png"
 },
 {
  id: "nebraska",
  espnId: 158,
  abbr: "NEB",
  school: "Nebraska",
  mascot: "Cornhuskers",
  conference: "Big Ten",
  colors: [
   "#d00000",
   "#ffffff"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Lincoln, NE",
   dome: false,
   capacity: 85458,
   altitudeFt: 1165,
   lat: 40.820682,
   lng: -96.705594
  },
  elo: 1538,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png"
 },
 {
  id: "northwestern",
  espnId: 77,
  abbr: "NU",
  school: "Northwestern",
  mascot: "Wildcats",
  conference: "Big Ten",
  colors: [
   "#582c83",
   "#ffffff"
  ],
  stadium: {
   name: "Lanny and Sharon Martin Stadium",
   city: "Evanston, IL",
   dome: false,
   capacity: 12023,
   altitudeFt: 587,
   lat: 42.058246,
   lng: -87.670876
  },
  elo: 1549,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png"
 },
 {
  id: "ohio-state",
  espnId: 194,
  abbr: "OSU",
  school: "Ohio State",
  mascot: "Buckeyes",
  conference: "Big Ten",
  colors: [
   "#ba0c2f",
   "#a7b1b7"
  ],
  stadium: {
   name: "Ohio Stadium",
   city: "Columbus, OH",
   dome: false,
   capacity: 102780,
   altitudeFt: 711,
   lat: 40.0016447,
   lng: -83.0197266
  },
  elo: 1925,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png"
 },
 {
  id: "oregon",
  espnId: 2483,
  abbr: "ORE",
  school: "Oregon",
  mascot: "Ducks",
  conference: "Big Ten",
  colors: [
   "#007030",
   "#fee11a"
  ],
  stadium: {
   name: "Autzen Stadium",
   city: "Eugene, OR",
   dome: false,
   capacity: 54000,
   altitudeFt: 418,
   lat: 44.0582712,
   lng: -123.0684883
  },
  elo: 1880,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png"
 },
 {
  id: "penn-state",
  espnId: 213,
  abbr: "PSU",
  school: "Penn State",
  mascot: "Nittany Lions",
  conference: "Big Ten",
  colors: [
   "#001e44",
   "#ffffff"
  ],
  stadium: {
   name: "Beaver Stadium",
   city: "University Park, PA",
   dome: false,
   capacity: 106572,
   altitudeFt: 1162,
   lat: 40.8121958,
   lng: -77.8561023
  },
  elo: 1802,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/213.png"
 },
 {
  id: "purdue",
  espnId: 2509,
  abbr: "PUR",
  school: "Purdue",
  mascot: "Boilermakers",
  conference: "Big Ten",
  colors: [
   "#ceb888",
   "#000000"
  ],
  stadium: {
   name: "Ross-Ade Stadium",
   city: "West Lafayette, IN",
   dome: false,
   capacity: 57282,
   altitudeFt: 648,
   lat: 40.4352253,
   lng: -86.9186843
  },
  elo: 1318,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png"
 },
 {
  id: "rutgers",
  espnId: 164,
  abbr: "RUTG",
  school: "Rutgers",
  mascot: "Scarlet Knights",
  conference: "Big Ten",
  colors: [
   "#ce0e2d",
   "#ffffff"
  ],
  stadium: {
   name: "SHI Stadium",
   city: "Piscataway, NJ",
   dome: false,
   capacity: 52454,
   altitudeFt: 62,
   lat: 40.513611,
   lng: -74.465278
  },
  elo: 1479,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png"
 },
 {
  id: "ucla",
  espnId: 26,
  abbr: "UCLA",
  school: "UCLA",
  mascot: "Bruins",
  conference: "Big Ten",
  colors: [
   "#2774ae",
   "#f2a900"
  ],
  stadium: {
   name: "Rose Bowl",
   city: "Pasadena, CA",
   dome: false,
   capacity: 88565,
   altitudeFt: 804,
   lat: 34.1613284,
   lng: -118.1676462
  },
  elo: 1381,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png"
 },
 {
  id: "usc",
  espnId: 30,
  abbr: "USC",
  school: "USC",
  mascot: "Trojans",
  conference: "Big Ten",
  colors: [
   "#990000",
   "#ffcc00"
  ],
  stadium: {
   name: "Los Angeles Memorial Coliseum",
   city: "Los Angeles, CA",
   dome: false,
   capacity: 77500,
   altitudeFt: 139,
   lat: 34.014167,
   lng: -118.287778
  },
  elo: 1763,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png"
 },
 {
  id: "washington",
  espnId: 264,
  abbr: "WASH",
  school: "Washington",
  mascot: "Huskies",
  conference: "Big Ten",
  colors: [
   "#33006f",
   "#e8d3a2"
  ],
  stadium: {
   name: "Husky Stadium",
   city: "Seattle, WA",
   dome: false,
   capacity: 70138,
   altitudeFt: 38,
   lat: 47.6503235,
   lng: -122.3015746
  },
  elo: 1744,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png"
 },
 {
  id: "wisconsin",
  espnId: 275,
  abbr: "WIS",
  school: "Wisconsin",
  mascot: "Badgers",
  conference: "Big Ten",
  colors: [
   "#a00000",
   "#ffffff"
  ],
  stadium: {
   name: "Camp Randall Stadium",
   city: "Madison, WI",
   dome: false,
   capacity: 80321,
   altitudeFt: 865,
   lat: 43.06994,
   lng: -89.4126943
  },
  elo: 1501,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png"
 },
 {
  id: "delaware",
  espnId: 48,
  abbr: "DEL",
  school: "Delaware",
  mascot: "Blue Hens",
  conference: "Conference USA",
  colors: [
   "#00539f",
   "#ffd200"
  ],
  stadium: {
   name: "Delaware Stadium",
   city: "Newark, DE",
   dome: false,
   capacity: 22000,
   altitudeFt: 94,
   lat: 39.6617428,
   lng: -75.7488224
  },
  elo: 1404,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/48.png"
 },
 {
  id: "florida-international",
  espnId: 2229,
  abbr: "FIU",
  school: "Florida International",
  mascot: "Panthers",
  conference: "Conference USA",
  colors: [
   "#091f3f",
   "#c3993f"
  ],
  stadium: {
   name: "Pitbull Stadium",
   city: "Miami, FL",
   dome: false,
   capacity: 20000,
   altitudeFt: 20,
   lat: 25.7525,
   lng: -80.37778
  },
  elo: 1382,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png"
 },
 {
  id: "jacksonville-state",
  espnId: 55,
  abbr: "JXST",
  school: "Jacksonville State",
  mascot: "Gamecocks",
  conference: "Conference USA",
  colors: [
   "#cc0000",
   "#000000"
  ],
  stadium: {
   name: "AmFirst Stadium",
   city: "Jacksonville, AL",
   dome: false,
   capacity: 24000,
   altitudeFt: 650,
   lat: 33.8201052,
   lng: -85.76647
  },
  elo: 1432,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png"
 },
 {
  id: "kennesaw-state",
  espnId: 338,
  abbr: "KENN",
  school: "Kennesaw State",
  mascot: "Owls",
  conference: "Conference USA",
  colors: [
   "#fdbb30",
   "#0b1315"
  ],
  stadium: {
   name: "Fifth Third Stadium",
   city: "Kennesaw, GA",
   dome: false,
   capacity: 11040,
   altitudeFt: 974,
   lat: 34.0289318,
   lng: -84.5676234
  },
  elo: 1373,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png"
 },
 {
  id: "liberty",
  espnId: 2335,
  abbr: "LIB",
  school: "Liberty",
  mascot: "Flames",
  conference: "Conference USA",
  colors: [
   "#0a254e",
   "#b72025"
  ],
  stadium: {
   name: "Williams Stadium",
   city: "Lynchburg, VA",
   dome: false,
   capacity: 25000,
   altitudeFt: 895,
   lat: 37.3544305,
   lng: -79.1750239
  },
  elo: 1703,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png"
 },
 {
  id: "middle-tennessee",
  espnId: 2393,
  abbr: "MTSU",
  school: "Middle Tennessee",
  mascot: "Blue Raiders",
  conference: "Conference USA",
  colors: [
   "#036eb7",
   "#ffffff"
  ],
  stadium: {
   name: "Johnny \"Red\" Floyd Stadium",
   city: "Murfreesboro, TN",
   dome: false,
   capacity: 30788,
   altitudeFt: 629,
   lat: 35.8511463,
   lng: -86.3681649
  },
  elo: 1276,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png"
 },
 {
  id: "missouri-state",
  espnId: 2623,
  abbr: "MOST",
  school: "Missouri State",
  mascot: "Bears",
  conference: "Conference USA",
  colors: [
   "#5e0009",
   "#ffffff"
  ],
  stadium: {
   name: "Plaster Sports Complex",
   city: "Springfield, MO",
   dome: false,
   capacity: 17337,
   altitudeFt: 1320,
   lat: 37.1976229,
   lng: -93.2798119
  },
  elo: 1385,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png"
 },
 {
  id: "new-mexico-state",
  espnId: 166,
  abbr: "NMSU",
  school: "New Mexico State",
  mascot: "Aggies",
  conference: "Conference USA",
  colors: [
   "#8c0b42",
   "#ffffff"
  ],
  stadium: {
   name: "Aggie Memorial Stadium",
   city: "Las Cruces, NM",
   dome: false,
   capacity: 28853,
   altitudeFt: 3964,
   lat: 32.2796202,
   lng: -106.7411148
  },
  elo: 1259,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png"
 },
 {
  id: "sam-houston",
  espnId: 2534,
  abbr: "SHSU",
  school: "Sam Houston",
  mascot: "Bearkats",
  conference: "Conference USA",
  colors: [
   "#f56423",
   "#ffffff"
  ],
  stadium: {
   name: "Elliott T. Bowers Stadium",
   city: "Huntsville, TX",
   dome: false,
   capacity: 14000,
   altitudeFt: 419,
   lat: 30.713926,
   lng: -95.5419802
  },
  elo: 1162,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png"
 },
 {
  id: "western-kentucky",
  espnId: 98,
  abbr: "WKU",
  school: "Western Kentucky",
  mascot: "Hilltoppers",
  conference: "Conference USA",
  colors: [
   "#c60c30",
   "#ffffff"
  ],
  stadium: {
   name: "Houchens Industries-L.T. Smith Stadium",
   city: "Bowling Green, KY",
   dome: false,
   capacity: 22113,
   altitudeFt: 507,
   lat: 36.9847901,
   lng: -86.4594041
  },
  elo: 1438,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png"
 },
 {
  id: "notre-dame",
  espnId: 87,
  abbr: "ND",
  school: "Notre Dame",
  mascot: "Fighting Irish",
  conference: "FBS Independents",
  colors: [
   "#0c2340",
   "#c99700"
  ],
  stadium: {
   name: "Notre Dame Stadium",
   city: "Notre Dame, IN",
   dome: false,
   capacity: 80795,
   altitudeFt: 730,
   lat: 41.698378,
   lng: -86.2339425
  },
  elo: 1995,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png"
 },
 {
  id: "uconn",
  espnId: 41,
  abbr: "CONN",
  school: "UConn",
  mascot: "Huskies",
  conference: "FBS Independents",
  colors: [
   "#000e2f",
   "#ffffff"
  ],
  stadium: {
   name: "Pratt & Whitney Stadium",
   city: "East Hartford, CT",
   dome: false,
   capacity: 40000,
   altitudeFt: 21,
   lat: 41.7595675,
   lng: -72.6187728
  },
  elo: 1484,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png"
 },
 {
  id: "akron",
  espnId: 2006,
  abbr: "AKR",
  school: "Akron",
  mascot: "Zips",
  conference: "Mid-American",
  colors: [
   "#041e42",
   "#a89968"
  ],
  stadium: {
   name: "InfoCision Stadium",
   city: "Akron, OH",
   dome: false,
   capacity: 30000,
   altitudeFt: 1054,
   lat: 41.0725534,
   lng: -81.5083408
  },
  elo: 925,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png"
 },
 {
  id: "ball-state",
  espnId: 2050,
  abbr: "BALL",
  school: "Ball State",
  mascot: "Cardinals",
  conference: "Mid-American",
  colors: [
   "#ba0c2f",
   "#ffffff"
  ],
  stadium: {
   name: "Scheumann Stadium",
   city: "Muncie, IN",
   dome: false,
   capacity: 22500,
   altitudeFt: 937,
   lat: 40.2159422,
   lng: -85.4161148
  },
  elo: 1173,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png"
 },
 {
  id: "bowling-green",
  espnId: 189,
  abbr: "BGSU",
  school: "Bowling Green",
  mascot: "Falcons",
  conference: "Mid-American",
  colors: [
   "#fd5000",
   "#4f2c1d"
  ],
  stadium: {
   name: "Doyt L. Perry Stadium",
   city: "Bowling Green, OH",
   dome: false,
   capacity: 24000,
   altitudeFt: 676,
   lat: 41.3780114,
   lng: -83.6225
  },
  elo: 1340,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png"
 },
 {
  id: "buffalo",
  espnId: 2084,
  abbr: "BUF",
  school: "Buffalo",
  mascot: "Bulls",
  conference: "Mid-American",
  colors: [
   "#005bbb",
   "#ffffff"
  ],
  stadium: {
   name: "UB Stadium",
   city: "Amherst, NY",
   dome: false,
   capacity: 30270,
   altitudeFt: 596,
   lat: 42.9991334,
   lng: -78.7775113
  },
  elo: 1365,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png"
 },
 {
  id: "central-michigan",
  espnId: 2117,
  abbr: "CMU",
  school: "Central Michigan",
  mascot: "Chippewas",
  conference: "Mid-American",
  colors: [
   "#6a0032",
   "#ffc82e"
  ],
  stadium: {
   name: "Kelly/Shorts Stadium",
   city: "Mount Pleasant, MI",
   dome: false,
   capacity: 30255,
   altitudeFt: 790,
   lat: 43.5777313,
   lng: -84.7709904
  },
  elo: 1321,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png"
 },
 {
  id: "eastern-michigan",
  espnId: 2199,
  abbr: "EMU",
  school: "Eastern Michigan",
  mascot: "Eagles",
  conference: "Mid-American",
  colors: [
   "#046a38",
   "#ffffff"
  ],
  stadium: {
   name: "Rynearson Stadium",
   city: "Ypsilanti, MI",
   dome: false,
   capacity: 30200,
   altitudeFt: 792,
   lat: 42.256126,
   lng: -83.647285
  },
  elo: 1350,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png"
 },
 {
  id: "kent-state",
  espnId: 2309,
  abbr: "KENT",
  school: "Kent State",
  mascot: "Golden Flashes",
  conference: "Mid-American",
  colors: [
   "#002664",
   "#eaab00"
  ],
  stadium: {
   name: "Dix Stadium",
   city: "Kent, OH",
   dome: false,
   capacity: 25319,
   altitudeFt: 1054,
   lat: 41.1390935,
   lng: -81.31346
  },
  elo: 1167,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png"
 },
 {
  id: "massachusetts",
  espnId: 113,
  abbr: "MASS",
  school: "Massachusetts",
  mascot: "Minutemen",
  conference: "Mid-American",
  colors: [
   "#881c1c",
   "#ffffff"
  ],
  stadium: {
   name: "Warren McGuirk Alumni Stadium",
   city: "Hadley, MA",
   dome: false,
   capacity: 17000,
   altitudeFt: 153,
   lat: 42.3773244,
   lng: -72.5360595
  },
  elo: 978,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png"
 },
 {
  id: "miami-oh",
  espnId: 193,
  abbr: "M-OH",
  school: "Miami (OH)",
  mascot: "RedHawks",
  conference: "Mid-American",
  colors: [
   "#c41230",
   "#ffffff"
  ],
  stadium: {
   name: "Yager Stadium",
   city: "Oxford, OH",
   dome: false,
   capacity: 24286,
   altitudeFt: 795,
   lat: 39.5197009,
   lng: -84.7330255
  },
  elo: 1364,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/193.png"
 },
 {
  id: "ohio",
  espnId: 195,
  abbr: "OHIO",
  school: "Ohio",
  mascot: "Bobcats",
  conference: "Mid-American",
  colors: [
   "#024230",
   "#ffffff"
  ],
  stadium: {
   name: "Peden Stadium",
   city: "Athens, OH",
   dome: false,
   capacity: 24000,
   altitudeFt: 637,
   lat: 39.3212794,
   lng: -82.1034315
  },
  elo: 1372,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png"
 },
 {
  id: "sacramento-state",
  espnId: 16,
  abbr: "SAC",
  school: "Sacramento State",
  mascot: "Hornets",
  conference: "Mid-American",
  colors: [
   "#00573c",
   "#cdb97d"
  ],
  stadium: {
   name: "Hornet Stadium",
   city: "Sacramento, CA",
   dome: false,
   capacity: 21195,
   altitudeFt: 40,
   lat: 38.5556718,
   lng: -121.4229607
  },
  elo: 1476,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/16.png"
 },
 {
  id: "toledo",
  espnId: 2649,
  abbr: "TOL",
  school: "Toledo",
  mascot: "Rockets",
  conference: "Mid-American",
  colors: [
   "#0b2240",
   "#ffcd00"
  ],
  stadium: {
   name: "Glass Bowl",
   city: "Toledo, OH",
   dome: false,
   capacity: 26038,
   altitudeFt: 595,
   lat: 41.6574777,
   lng: -83.6135652
  },
  elo: 1597,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png"
 },
 {
  id: "western-michigan",
  espnId: 2711,
  abbr: "WMU",
  school: "Western Michigan",
  mascot: "Broncos",
  conference: "Mid-American",
  colors: [
   "#532e1f",
   "#f1c500"
  ],
  stadium: {
   name: "Waldo Stadium",
   city: "Kalamazoo, MI",
   dome: false,
   capacity: 30200,
   altitudeFt: 800,
   lat: 42.2860064,
   lng: -85.6007573
  },
  elo: 1530,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png"
 },
 {
  id: "air-force",
  espnId: 2005,
  abbr: "AF",
  school: "Air Force",
  mascot: "Falcons",
  conference: "Mountain West",
  colors: [
   "#003594",
   "#ffffff"
  ],
  stadium: {
   name: "Falcon Stadium",
   city: "Colorado Springs, CO",
   dome: false,
   capacity: 46692,
   altitudeFt: 6644,
   lat: 38.9969701,
   lng: -104.8436165
  },
  elo: 1424,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png"
 },
 {
  id: "hawaii",
  espnId: 62,
  abbr: "HAW",
  school: "Hawai'i",
  mascot: "Rainbow Warriors",
  conference: "Mountain West",
  colors: [
   "#024731",
   "#000000"
  ],
  stadium: {
   name: "Clarence T.C. Ching Athletics Complex",
   city: "Honolulu, HI",
   dome: false,
   capacity: 15194,
   altitudeFt: 66,
   lat: 21.294294,
   lng: -157.819338
  },
  elo: 1454,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png"
 },
 {
  id: "nevada",
  espnId: 2440,
  abbr: "NEV",
  school: "Nevada",
  mascot: "Wolf Pack",
  conference: "Mountain West",
  colors: [
   "#041e42",
   "#8a8d8f"
  ],
  stadium: {
   name: "Mackay Stadium",
   city: "Reno, NV",
   dome: false,
   capacity: 27000,
   altitudeFt: 4615,
   lat: 39.5469459,
   lng: -119.8175435
  },
  elo: 1351,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png"
 },
 {
  id: "new-mexico",
  espnId: 167,
  abbr: "UNM",
  school: "New Mexico",
  mascot: "Lobos",
  conference: "Mountain West",
  colors: [
   "#ba0c2f",
   "#a7a8aa"
  ],
  stadium: {
   name: "University Stadium",
   city: "Albuquerque, NM",
   dome: false,
   capacity: 39224,
   altitudeFt: 5100,
   lat: 35.0669479,
   lng: -106.6283225
  },
  elo: 1496,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png"
 },
 {
  id: "north-dakota-state",
  espnId: 2449,
  abbr: "NDSU",
  school: "North Dakota State",
  mascot: "Bison",
  conference: "Mountain West",
  colors: [
   "#00583d",
   "#ffc425"
  ],
  stadium: {
   name: "Fargodome",
   city: "Fargo, ND",
   dome: true,
   capacity: 18700,
   altitudeFt: 901,
   lat: 46.9029938,
   lng: -96.8003251
  },
  elo: 1562,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png"
 },
 {
  id: "northern-illinois",
  espnId: 2459,
  abbr: "NIU",
  school: "Northern Illinois",
  mascot: "Huskies",
  conference: "Mountain West",
  colors: [
   "#c8102e",
   "#000000"
  ],
  stadium: {
   name: "Huskie Stadium",
   city: "DeKalb, IL",
   dome: false,
   capacity: 23595,
   altitudeFt: 878,
   lat: 41.9339586,
   lng: -88.7778357
  },
  elo: 1322,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png"
 },
 {
  id: "san-jose-state",
  espnId: 23,
  abbr: "SJSU",
  school: "San José State",
  mascot: "Spartans",
  conference: "Mountain West",
  colors: [
   "#0055a2",
   "#e5a823"
  ],
  stadium: {
   name: "CEFCU Stadium",
   city: "San Jose, CA",
   dome: false,
   capacity: 30456,
   altitudeFt: 93,
   lat: 37.3196675,
   lng: -121.8682962
  },
  elo: 1395,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png"
 },
 {
  id: "unlv",
  espnId: 2439,
  abbr: "UNLV",
  school: "UNLV",
  mascot: "Rebels",
  conference: "Mountain West",
  colors: [
   "#cf0a2c",
   "#cac8c8"
  ],
  stadium: {
   name: "Allegiant Stadium",
   city: "Las Vegas, NV",
   dome: true,
   capacity: 65000,
   altitudeFt: 2185,
   lat: 36.09075,
   lng: -115.183722
  },
  elo: 1566,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png"
 },
 {
  id: "utep",
  espnId: 2638,
  abbr: "UTEP",
  school: "UTEP",
  mascot: "Miners",
  conference: "Mountain West",
  colors: [
   "#ff8200",
   "#041e42"
  ],
  stadium: {
   name: "Sun Bowl",
   city: "El Paso, TX",
   dome: false,
   capacity: 51500,
   altitudeFt: 3884,
   lat: 31.7733353,
   lng: -106.507957
  },
  elo: 1256,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png"
 },
 {
  id: "wyoming",
  espnId: 2751,
  abbr: "WYO",
  school: "Wyoming",
  mascot: "Cowboys",
  conference: "Mountain West",
  colors: [
   "#492f24",
   "#ffc425"
  ],
  stadium: {
   name: "War Memorial Stadium",
   city: "Laramie, WY",
   dome: false,
   capacity: 29181,
   altitudeFt: 7219,
   lat: 41.31161,
   lng: -105.5681384
  },
  elo: 1363,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png"
 },
 {
  id: "boise-state",
  espnId: 68,
  abbr: "BOIS",
  school: "Boise State",
  mascot: "Broncos",
  conference: "Pac-12",
  colors: [
   "#0033a0",
   "#d64309"
  ],
  stadium: {
   name: "Albertsons Stadium",
   city: "Boise, ID",
   dome: false,
   capacity: 36387,
   altitudeFt: 2701,
   lat: 43.6028839,
   lng: -116.1958882
  },
  elo: 1562,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png"
 },
 {
  id: "colorado-state",
  espnId: 36,
  abbr: "CSU",
  school: "Colorado State",
  mascot: "Rams",
  conference: "Pac-12",
  colors: [
   "#1e4d2b",
   "#c8c372"
  ],
  stadium: {
   name: "Canvas Stadium",
   city: "Fort Collins, CO",
   dome: false,
   capacity: 36500,
   altitudeFt: 5015,
   lat: 40.570015,
   lng: -105.088435
  },
  elo: 1273,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png"
 },
 {
  id: "fresno-state",
  espnId: 278,
  abbr: "FRES",
  school: "Fresno State",
  mascot: "Bulldogs",
  conference: "Pac-12",
  colors: [
   "#c41230",
   "#13284c"
  ],
  stadium: {
   name: "Valley Children's Stadium",
   city: "Fresno, CA",
   dome: false,
   capacity: 41031,
   altitudeFt: 337,
   lat: 36.8143527,
   lng: -119.7580092
  },
  elo: 1532,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png"
 },
 {
  id: "oregon-state",
  espnId: 204,
  abbr: "ORST",
  school: "Oregon State",
  mascot: "Beavers",
  conference: "Pac-12",
  colors: [
   "#dc4405",
   "#000000"
  ],
  stadium: {
   name: "Reser Stadium",
   city: "Corvallis, OR",
   dome: false,
   capacity: 43363,
   altitudeFt: 220,
   lat: 44.5594559,
   lng: -123.2814341
  },
  elo: 1266,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png"
 },
 {
  id: "san-diego-state",
  espnId: 21,
  abbr: "SDSU",
  school: "San Diego State",
  mascot: "Aztecs",
  conference: "Pac-12",
  colors: [
   "#a6192e",
   "#000000"
  ],
  stadium: {
   name: "Snapdragon Stadium",
   city: "San Diego, CA",
   dome: false,
   capacity: 35000,
   altitudeFt: 203,
   lat: 32.784444,
   lng: -117.122833
  },
  elo: 1518,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png"
 },
 {
  id: "texas-state",
  espnId: 326,
  abbr: "TXST",
  school: "Texas State",
  mascot: "Bobcats",
  conference: "Pac-12",
  colors: [
   "#501214",
   "#6a5638"
  ],
  stadium: {
   name: "Bobcat Stadium",
   city: "San Marcos, TX",
   dome: false,
   capacity: 30000,
   altitudeFt: 584,
   lat: 29.8910008,
   lng: -97.9255735
  },
  elo: 1570,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png"
 },
 {
  id: "utah-state",
  espnId: 328,
  abbr: "USU",
  school: "Utah State",
  mascot: "Aggies",
  conference: "Pac-12",
  colors: [
   "#0f2439",
   "#ffffff"
  ],
  stadium: {
   name: "Maverik Stadium",
   city: "Logan, UT",
   dome: false,
   capacity: 25513,
   altitudeFt: 4685,
   lat: 41.7517394,
   lng: -111.8116007
  },
  elo: 1376,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png"
 },
 {
  id: "washington-state",
  espnId: 265,
  abbr: "WSU",
  school: "Washington State",
  mascot: "Cougars",
  conference: "Pac-12",
  colors: [
   "#a60f2d",
   "#4d4d4d"
  ],
  stadium: {
   name: "Gesa Field",
   city: "Pullman, WA",
   dome: false,
   capacity: 32952,
   altitudeFt: 2539,
   lat: 46.731831,
   lng: -117.1604991
  },
  elo: 1619,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png"
 },
 {
  id: "alabama",
  espnId: 333,
  abbr: "ALA",
  school: "Alabama",
  mascot: "Crimson Tide",
  conference: "SEC",
  colors: [
   "#9e1b32",
   "#ffffff"
  ],
  stadium: {
   name: "Bryant-Denny Stadium",
   city: "Tuscaloosa, AL",
   dome: false,
   capacity: 101821,
   altitudeFt: 230,
   lat: 33.2082752,
   lng: -87.5503836
  },
  elo: 1738,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png"
 },
 {
  id: "arkansas",
  espnId: 8,
  abbr: "ARK",
  school: "Arkansas",
  mascot: "Razorbacks",
  conference: "SEC",
  colors: [
   "#a32136",
   "#ffffff"
  ],
  stadium: {
   name: "Razorback Stadium",
   city: "Fayetteville, AR",
   dome: false,
   capacity: 80000,
   altitudeFt: 1325,
   lat: 36.0680662,
   lng: -94.1789534
  },
  elo: 1547,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/8.png"
 },
 {
  id: "auburn",
  espnId: 2,
  abbr: "AUB",
  school: "Auburn",
  mascot: "Tigers",
  conference: "SEC",
  colors: [
   "#0c2340",
   "#f26522"
  ],
  stadium: {
   name: "Jordan-Hare Stadium",
   city: "Auburn, AL",
   dome: false,
   capacity: 87451,
   altitudeFt: 660,
   lat: 32.6025532,
   lng: -85.4897479
  },
  elo: 1613,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png"
 },
 {
  id: "florida",
  espnId: 57,
  abbr: "FLA",
  school: "Florida",
  mascot: "Gators",
  conference: "SEC",
  colors: [
   "#0021a5",
   "#fa4616"
  ],
  stadium: {
   name: "Ben Hill Griffin Stadium",
   city: "Gainesville, FL",
   dome: false,
   capacity: 88548,
   altitudeFt: 148,
   lat: 29.6499357,
   lng: -82.3485788
  },
  elo: 1562,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png"
 },
 {
  id: "georgia",
  espnId: 61,
  abbr: "UGA",
  school: "Georgia",
  mascot: "Bulldogs",
  conference: "SEC",
  colors: [
   "#ba0c2f",
   "#2c2a29"
  ],
  stadium: {
   name: "Sanford Stadium",
   city: "Athens, GA",
   dome: false,
   capacity: 92746,
   altitudeFt: 611,
   lat: 33.9498197,
   lng: -83.3733813
  },
  elo: 1871,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png"
 },
 {
  id: "kentucky",
  espnId: 96,
  abbr: "UK",
  school: "Kentucky",
  mascot: "Wildcats",
  conference: "SEC",
  colors: [
   "#0033a0",
   "#ffffff"
  ],
  stadium: {
   name: "Kroger Field",
   city: "Lexington, KY",
   dome: false,
   capacity: 61000,
   altitudeFt: 1009,
   lat: 38.0220905,
   lng: -84.5053408
  },
  elo: 1476,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png"
 },
 {
  id: "lsu",
  espnId: 99,
  abbr: "LSU",
  school: "LSU",
  mascot: "Tigers",
  conference: "SEC",
  colors: [
   "#461d7c",
   "#fdd023"
  ],
  stadium: {
   name: "Tiger Stadium",
   city: "Baton Rouge, LA",
   dome: false,
   capacity: 102321,
   altitudeFt: 25,
   lat: 30.412035,
   lng: -91.1838163
  },
  elo: 1616,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/99.png"
 },
 {
  id: "mississippi-state",
  espnId: 344,
  abbr: "MSST",
  school: "Mississippi State",
  mascot: "Bulldogs",
  conference: "SEC",
  colors: [
   "#5d1725",
   "#c1c6c8"
  ],
  stadium: {
   name: "Davis Wade Stadium",
   city: "Starkville, MS",
   dome: false,
   capacity: 61337,
   altitudeFt: 362,
   lat: 33.4563403,
   lng: -88.7933652
  },
  elo: 1478,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png"
 },
 {
  id: "missouri",
  espnId: 142,
  abbr: "MIZ",
  school: "Missouri",
  mascot: "Tigers",
  conference: "SEC",
  colors: [
   "#f1b82d",
   "#000000"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Columbia, MO",
   dome: false,
   capacity: 71168,
   altitudeFt: 698,
   lat: 38.9358491,
   lng: -92.3332009
  },
  elo: 1666,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png"
 },
 {
  id: "oklahoma",
  espnId: 201,
  abbr: "OU",
  school: "Oklahoma",
  mascot: "Sooners",
  conference: "SEC",
  colors: [
   "#841617",
   "#ffffff"
  ],
  stadium: {
   name: "Memorial Stadium",
   city: "Norman, OK",
   dome: false,
   capacity: 86112,
   altitudeFt: 1165,
   lat: 35.2058537,
   lng: -97.4423145
  },
  elo: 1706,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/201.png"
 },
 {
  id: "ole-miss",
  espnId: 145,
  abbr: "MISS",
  school: "Ole Miss",
  mascot: "Rebels",
  conference: "SEC",
  colors: [
   "#13294b",
   "#cf142b"
  ],
  stadium: {
   name: "Vaught-Hemingway Stadium",
   city: "Oxford, MS",
   dome: false,
   capacity: 64038,
   altitudeFt: 482,
   lat: 34.3619837,
   lng: -89.5342076
  },
  elo: 1839,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png"
 },
 {
  id: "south-carolina",
  espnId: 2579,
  abbr: "SC",
  school: "South Carolina",
  mascot: "Gamecocks",
  conference: "SEC",
  colors: [
   "#73000a",
   "#000000"
  ],
  stadium: {
   name: "Williams-Brice Stadium",
   city: "Columbia, SC",
   dome: false,
   capacity: 80250,
   altitudeFt: 199,
   lat: 33.9730239,
   lng: -81.0191726
  },
  elo: 1631,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png"
 },
 {
  id: "tennessee",
  espnId: 2633,
  abbr: "TENN",
  school: "Tennessee",
  mascot: "Volunteers",
  conference: "SEC",
  colors: [
   "#ff8200",
   "#ffffff"
  ],
  stadium: {
   name: "Neyland Stadium",
   city: "Knoxville, TN",
   dome: false,
   capacity: 102455,
   altitudeFt: 892,
   lat: 35.9550131,
   lng: -83.9250128
  },
  elo: 1691,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png"
 },
 {
  id: "texas",
  espnId: 251,
  abbr: "TEX",
  school: "Texas",
  mascot: "Longhorns",
  conference: "SEC",
  colors: [
   "#bf5700",
   "#ffffff"
  ],
  stadium: {
   name: "DKR-Texas Memorial Stadium",
   city: "Austin, TX",
   dome: false,
   capacity: 100119,
   altitudeFt: 526,
   lat: 30.2836813,
   lng: -97.7325345
  },
  elo: 1784,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png"
 },
 {
  id: "texas-am",
  espnId: 245,
  abbr: "TA&M",
  school: "Texas A&M",
  mascot: "Aggies",
  conference: "SEC",
  colors: [
   "#500000",
   "#ffffff"
  ],
  stadium: {
   name: "Kyle Field",
   city: "College Station, TX",
   dome: false,
   capacity: 102733,
   altitudeFt: 357,
   lat: 30.6098891,
   lng: -96.3403828
  },
  elo: 1748,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/245.png"
 },
 {
  id: "vanderbilt",
  espnId: 238,
  abbr: "VAN",
  school: "Vanderbilt",
  mascot: "Commodores",
  conference: "SEC",
  colors: [
   "#000000",
   "#cfae70"
  ],
  stadium: {
   name: "FirstBank Stadium",
   city: "Nashville, TN",
   dome: false,
   capacity: 40351,
   altitudeFt: 525,
   lat: 36.1440455,
   lng: -86.8088942
  },
  elo: 1753,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png"
 },
 {
  id: "app-state",
  espnId: 2026,
  abbr: "APP",
  school: "App State",
  mascot: "Mountaineers",
  conference: "Sun Belt",
  colors: [
   "#000000",
   "#ffcd00"
  ],
  stadium: {
   name: "Kidd Brewer Stadium",
   city: "Boone, NC",
   dome: false,
   capacity: 30000,
   altitudeFt: 3253,
   lat: 36.2114267,
   lng: -81.6854278
  },
  elo: 1310,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png"
 },
 {
  id: "arkansas-state",
  espnId: 2032,
  abbr: "ARST",
  school: "Arkansas State",
  mascot: "Red Wolves",
  conference: "Sun Belt",
  colors: [
   "#cc092f",
   "#000000"
  ],
  stadium: {
   name: "Centennial Bank Stadium",
   city: "Jonesboro, AR",
   dome: false,
   capacity: 30382,
   altitudeFt: 294,
   lat: 35.8488977,
   lng: -90.6677436
  },
  elo: 1378,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png"
 },
 {
  id: "coastal-carolina",
  espnId: 324,
  abbr: "CCU",
  school: "Coastal Carolina",
  mascot: "Chanticleers",
  conference: "Sun Belt",
  colors: [
   "#006f71",
   "#a27752"
  ],
  stadium: {
   name: "Brooks Stadium",
   city: "Conway, SC",
   dome: false,
   capacity: 21000,
   altitudeFt: 45,
   lat: 33.7928506,
   lng: -79.0166946
  },
  elo: 1275,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png"
 },
 {
  id: "georgia-southern",
  espnId: 290,
  abbr: "GASO",
  school: "Georgia Southern",
  mascot: "Eagles",
  conference: "Sun Belt",
  colors: [
   "#041e42",
   "#ffffff"
  ],
  stadium: {
   name: "Allen E. Paulson Stadium",
   city: "Statesboro, GA",
   dome: false,
   capacity: 25000,
   altitudeFt: 201,
   lat: 32.4122471,
   lng: -81.7849296
  },
  elo: 1376,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png"
 },
 {
  id: "georgia-state",
  espnId: 2247,
  abbr: "GAST",
  school: "Georgia State",
  mascot: "Panthers",
  conference: "Sun Belt",
  colors: [
   "#0039a6",
   "#ffffff"
  ],
  stadium: {
   name: "Center Parc Stadium",
   city: "Atlanta, GA",
   dome: false,
   capacity: 25000,
   altitudeFt: 942,
   lat: 33.735267,
   lng: -84.389949
  },
  elo: 1241,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png"
 },
 {
  id: "james-madison",
  espnId: 256,
  abbr: "JMU",
  school: "James Madison",
  mascot: "Dukes",
  conference: "Sun Belt",
  colors: [
   "#450084",
   "#cbb677"
  ],
  stadium: {
   name: "Bridgeforth Stadium",
   city: "Harrisonburg, VA",
   dome: false,
   capacity: 24877,
   altitudeFt: 1310,
   lat: 38.4352919,
   lng: -78.8729349
  },
  elo: 1770,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png"
 },
 {
  id: "louisiana",
  espnId: 309,
  abbr: "UL",
  school: "Louisiana",
  mascot: "Ragin' Cajuns",
  conference: "Sun Belt",
  colors: [
   "#ce181e",
   "#000000"
  ],
  stadium: {
   name: "Cajun Field",
   city: "Lafayette, LA",
   dome: false,
   capacity: 41426,
   altitudeFt: 12,
   lat: 30.2158434,
   lng: -92.0417371
  },
  elo: 1389,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png"
 },
 {
  id: "louisiana-tech",
  espnId: 2348,
  abbr: "LT",
  school: "Louisiana Tech",
  mascot: "Bulldogs",
  conference: "Sun Belt",
  colors: [
   "#003087",
   "#cb333b"
  ],
  stadium: {
   name: "Joe Aillet Stadium",
   city: "Ruston, LA",
   dome: false,
   capacity: 28019,
   altitudeFt: 239,
   lat: 32.5321487,
   lng: -92.6560019
  },
  elo: 1454,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png"
 },
 {
  id: "marshall",
  espnId: 276,
  abbr: "MRSH",
  school: "Marshall",
  mascot: "Thundering Herd",
  conference: "Sun Belt",
  colors: [
   "#00b140",
   "#000000"
  ],
  stadium: {
   name: "Joan C. Edwards Stadium",
   city: "Huntington, WV",
   dome: false,
   capacity: 38016,
   altitudeFt: 537,
   lat: 38.4247042,
   lng: -82.4214412
  },
  elo: 1478,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png"
 },
 {
  id: "old-dominion",
  espnId: 295,
  abbr: "ODU",
  school: "Old Dominion",
  mascot: "Monarchs",
  conference: "Sun Belt",
  colors: [
   "#043657",
   "#98c5ea"
  ],
  stadium: {
   name: "S.B. Ballard Stadium",
   city: "Norfolk, VA",
   dome: false,
   capacity: 20118,
   altitudeFt: 10,
   lat: 36.8889533,
   lng: -76.3049175
  },
  elo: 1336,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png"
 },
 {
  id: "south-alabama",
  espnId: 6,
  abbr: "USA",
  school: "South Alabama",
  mascot: "Jaguars",
  conference: "Sun Belt",
  colors: [
   "#00205b",
   "#bf0d3e"
  ],
  stadium: {
   name: "Hancock Whitney Stadium",
   city: "Mobile, AL",
   dome: false,
   capacity: 25450,
   altitudeFt: 148,
   lat: 30.696904,
   lng: -88.192013
  },
  elo: 1390,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png"
 },
 {
  id: "southern-miss",
  espnId: 2572,
  abbr: "USM",
  school: "Southern Miss",
  mascot: "Golden Eagles",
  conference: "Sun Belt",
  colors: [
   "#ffc72c",
   "#231f20"
  ],
  stadium: {
   name: "M. M. Roberts Stadium",
   city: "Hattiesburg, MS",
   dome: false,
   capacity: 36000,
   altitudeFt: 212,
   lat: 31.3289321,
   lng: -89.3318118
  },
  elo: 1350,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png"
 },
 {
  id: "troy",
  espnId: 2653,
  abbr: "TROY",
  school: "Troy",
  mascot: "Trojans",
  conference: "Sun Belt",
  colors: [
   "#862633",
   "#b1b1b1"
  ],
  stadium: {
   name: "Veterans Memorial Stadium",
   city: "Troy, AL",
   dome: false,
   capacity: 30000,
   altitudeFt: 508,
   lat: 31.7995565,
   lng: -85.9518328
  },
  elo: 1422,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png"
 },
 {
  id: "ul-monroe",
  espnId: 2433,
  abbr: "ULM",
  school: "UL Monroe",
  mascot: "Warhawks",
  conference: "Sun Belt",
  colors: [
   "#840029",
   "#fdb913"
  ],
  stadium: {
   name: "Malone Stadium",
   city: "Monroe, LA",
   dome: false,
   capacity: 27617,
   altitudeFt: 75,
   lat: 32.5308089,
   lng: -92.0660602
  },
  elo: 1177,
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png"
 }
];
